input_data_path: "./data/raw/heart_cleveland_upload.csv"
use_mlflow: True
name_training_in_mlflow: 'classification'
train_params:
  model_type: "LogisticRegression"
  output_model_path: "./models/models/model.pkl"
  output_transformer_path: "./models/transformers/transform.pkl"
  output_metric_path: "./models/evaluations/evaluation.json"
  random_state: 32

download_params:
  dataset_name: "cherngs/heart-disease-cleveland-uci"
  output_folder: "data/raw/"
  username: "andrey506"
  api_key: "c75881935efe32578a658b3c56218d11"

splitting_params:
  val_size: 0.2
  random_state: 3

feature_params:
  process_categorical: True
  categorical_features:
    - "fbs"
    - "sex"
    - "cp"
    - "restecg"
    - "exang"
    - "thal"
    - "slope"
    - "ca"
  process_numerical: True
  numerical_features:
    - "chol"
    - "age"
    - "oldpeak"
    - "thalach"
    - "trestbps"
  features_to_drop:
    - "cp"
    - "exang"
    - "thalach"
    - "oldpeak"
    - "ca"
    - "thal"
  target_col: "condition"